import group_A/xxxxxx
import group_B/xxxxxxx

print("initialising")
print("---------------------------")
print("Group A")
print("---------------------------")
print("Mandatory question 1")
print("---------------------------")
print("Mandatory question 2")
print("---------------------------")
print("Mandatory question 3")
print("---------------------------")
print("Optional question 1")
print("---------------------------")
print("Optional question 2")
print("---------------------------")
print("Optional question 3")

print("---------------------------")
print("Group B")
print("---------------------------")
print("Mandatory question 1")
print("---------------------------")
print("Mandatory question 2")
print("---------------------------")
print("Mandatory question 3")
print("---------------------------")
print("Optional question 1")
print("---------------------------")
print("Optional question 2")
print("---------------------------")
print("Optional question 3")
